/**
 * Skill generator using the Anthropic API.
 * buildSkill(description, db) → { slug, displayName, skillMd, scriptContent, scriptFilename }
 */

import { getSecret } from "../orchestrator/connections.js";

const MODEL = "claude-sonnet-4-6";

const SYSTEM_PROMPT = `You are a skill builder for ClawOS, an AI orchestration system.
Given a description of a skill, generate a SKILL.md file and a shell script that implements it.

Output ONLY in this exact XML format — no other text before or after:

<slug>short-kebab-case-identifier</slug>
<displayName>Human Readable Name</displayName>
<skillMd>---
name: {slug}
version: "1.0.0"
homepage: https://clawhub.ai/skills/{slug}
description: {one-line description}
required_env:
  - ENV_VAR_NAME: "What this key is for"
---

# {displayName}

{2-3 sentence description of what the skill does and why it's useful.}

## Usage

\`\`\`bash
./{slug}.sh [arguments]
\`\`\`

## Setup

1. Obtain the required API keys listed above.
2. Export them in your shell or add them to your \`.env\` file.
3. Run the script directly or integrate it with ClawOS.
</skillMd>
<script filename="{slug}.sh">
#!/usr/bin/env bash
set -euo pipefail

# {displayName}
# Generated by ClawOS Skill Builder

{script content — clean, commented bash that implements the skill}
</script>`;

/**
 * @param {string} description  User-provided skill description
 * @param {import('better-sqlite3').Database} db
 * @returns {Promise<{ slug: string; displayName: string; skillMd: string; scriptContent: string; scriptFilename: string }>}
 */
export async function buildSkill(description, db) {
  const secrets = getSecret(db, "anthropic");
  if (!secrets?.api_key) {
    throw new Error("Anthropic API key not configured. Add it in Settings → Connections.");
  }

  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": secrets.api_key,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: MODEL,
      max_tokens: 4096,
      system: SYSTEM_PROMPT,
      messages: [{ role: "user", content: `Build a skill: ${description}` }],
    }),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(`Anthropic API error ${res.status}: ${err.error?.message ?? "unknown"}`);
  }

  const data = await res.json();
  const text = data.content?.[0]?.text ?? "";

  // Parse XML tags
  const slug        = text.match(/<slug>([\s\S]*?)<\/slug>/)?.[1]?.trim()               ?? "custom-skill";
  const displayName = text.match(/<displayName>([\s\S]*?)<\/displayName>/)?.[1]?.trim() ?? "Custom Skill";
  const skillMd     = text.match(/<skillMd>([\s\S]*?)<\/skillMd>/)?.[1]?.trim()         ?? "";
  const scriptMatch = text.match(/<script filename="([^"]+)">([\s\S]*?)<\/script>/);
  const scriptFilename = scriptMatch?.[1] ?? `${slug}.sh`;
  const scriptContent  = scriptMatch?.[2]?.trim() ?? "";

  return { slug, displayName, skillMd, scriptContent, scriptFilename };
}
